name: vibha_browser
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^3.0.0
  supabase_flutter: ^1.0.0
  shared_preferences: ^2.0.0
  postgrest: ^2.0.0
  permission_handler: ^10.0.0
  sentry_flutter: ^7.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true